# Generated by Django 3.1.6 on 2021-02-18 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_date', models.DateTimeField(auto_created=True)),
                ('session', models.CharField(max_length=36)),
                ('category', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('data', models.JSONField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
