# Generated by Django 3.1.6 on 2021-02-18 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='session',
            new_name='session_id',
        ),
    ]
