# Generated by Django 3.1.6 on 2021-02-20 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210219_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorlog',
            name='error',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='event',
            name='session_id',
            field=models.CharField(max_length=36),
        ),
        migrations.AlterField(
            model_name='event',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
